name: Test CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Run test
      run: mvn test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: target/surefire-reports/*.xml
    - name: Code Coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: jacoco.xml
        directory: ./target/site/jacoco/
